parameters:
    terminal.command.lock.repository.class: EXS\TerminalBundle\Entity\Repository\CommandLockRepository
    terminal.command.lock.manager.class: EXS\TerminalBundle\Services\Managers\CommandLockManager
    terminal.output.manager.class: EXS\TerminalBundle\Services\Managers\OutputManager
    terminal.output.listener.class: EXS\TerminalBundle\Services\Listeners\ConsoleLogOutputEventListener
    terminal.command.lock.listener.class: EXS\TerminalBundle\Services\Listeners\CommandLockEventListener

services:
    terminal.commandlock.repository:
        class: %terminal.command.lock.repository.class%
        arguments: [EXSTerminalBundle:CommandLock]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    terminal.commandlock.manager:
        class: %terminal.command.lock.manager.class%
        arguments: [@doctrine.orm.entity_manager, @terminal.commandlock.repository]
    terminal.output.manager:
        class: %terminal.output.manager.class%
        calls:
            - [setContainer,[ @service_container ]]
            - [setManager,[ @doctrine.orm.entity_manager ]]
    terminal.output.listener:
        class: %terminal.output.listener.class%
        arguments: [@terminal.output.manager,@exs.exception_listener]
        tags:
            - { name: kernel.event_subscriber }
    terminal.commandlock.listener:
        class: %terminal.command.lock.listener.class%
        arguments: [@terminal.commandlock.manager,@exs.exception_listener]
        tags:
            - { name: kernel.event_subscriber }
