parameters:
    terminal.email.manager.class: EXS\TerminalBundle\Services\Managers\EmailManager
    terminal.commandlock.subscriber.class: EXS\TerminalBundle\Services\Subscribers\CommandLockSubscriber
    terminal.commandlock.manager.class: EXS\TerminalBundle\Services\Managers\CommandLockManager
    terminal.commandlock.repository.class: EXS\TerminalBundle\Entity\Repository\CommandLockRepository
    terminal.output.subscriber.class: EXS\TerminalBundle\Services\Subscribers\ConsoleLogOutputSubscriber
    terminal.output.manager.class: EXS\TerminalBundle\Services\Managers\OutputManager

services:
    terminal.email.manager:
        class: %terminal.email.manager.class%
        arguments: [ @templating, @mailer, %exs_terminal.email% ]

    terminal.commandlock.subscriber:
        class: %terminal.commandlock.subscriber.class%
        arguments: [ @terminal.commandlock.manager, @terminal.email.manager ]
        tags:
            - { name: kernel.event_subscriber }

    terminal.commandlock.manager:
        class: %terminal.commandlock.manager.class%
        arguments: [ @doctrine, @terminal.commandlock.repository ]

    terminal.commandlock.repository:
        class: %terminal.commandlock.repository.class%
        arguments: [ 'EXSTerminalBundle:CommandLock' ]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository

    terminal.output.subscriber:
        class: %terminal.output.subscriber.class%
        tags:
            - { name: kernel.event_subscriber }

    terminal.output.manager:
        class: %terminal.output.manager.class%
        calls:
            - [ 'setContainer', [ @service_container ] ]
            - [ 'setManagerRegistry', [ @doctrine ] ]
