<?php

namespace EXS\TerminalBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use EXS\TerminalBundle\Entity\CommandLock;
/**
 * Description of CommandLockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * Created      03/26/2015
 * @author      Charles Weiss & Mathieu Delisle
 * @copyright   Copyright 2015 ExSitu Marketing.
 */
class CommandLockRepository extends EntityRepository
{
    /**
     * Gets setting from DB or default setting entity.
     * Returns entity (Setting)
     *
     * @return CommandLock
     */
    public function getCommandLockByName($name = '')
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM EXSTerminalBundle:CommandLock c WHERE c.lockName = :name")
            ->setMaxResults(1)
            ->setParameter("name", $name);
        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
            $newCommandLock = new CommandLock();
            $newCommandLock->setLockName($name);

            return $newCommandLock;
        }
    }
}
